source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Chop_Example', :exclusive => true do
  pod 'Chop', :path => '../'
end

target 'Chop_Tests', :exclusive => true do
  pod 'Chop', :path => '../'
end
