language: objective-c
osx_image: xcode7.1

cache: cocoapods
podfile: Example/Podfile 

install:
 - gem install xcpretty
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
 
script:
 - set -o pipefail && xcodebuild test -workspace Example/Chop.xcworkspace -scheme Chop-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES | xcpretty
 - pod lib lint

after_success:
 - bash <(curl -s https://codecov.io/bash) -J 'Chop'
