language: objective-c
osx_image: xcode9

rvm: 2.2
cache: cocoapods
podfile: test/Podfile 

install:
 - gem install xcpretty
 - gem install xcpretty-travis-formatter
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --no-repo-update --project-directory=test
 
script:
 - set -o pipefail && xcodebuild test -workspace test/Chop.xcworkspace -scheme ChopTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty -f `xcpretty-travis-formatter`
 - pod lib lint

after_success:
 - bash <(curl -s https://codecov.io/bash) -J 'Chop'
